# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # --- Standard Hooks ---
  # For basic file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files

  # --- Ruff Linter & Formatter ---
  # Fast, efficient linting and formatting on changed files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2 # Match your pyproject.toml version
    hooks:
      - id: ruff
        args: [--fix, --ignore=E501]
      - id: ruff-format

  # --- Type Checking Only ---
  # Fast type checking without slow tests
  - repo: local
    hooks:
      - id: type-check
        name: Run type-checking only
        entry: /opt/homebrew/bin/just type-check
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
