# GSC-CLI 應用程式預設設定

[paths]
# 所有路徑都是相對於專案根目錄
data_dir = "data"
log_dir = "logs"
report_dir = "reports"
config_dir = "cred"
backup_dir = "data/backups"

[database]
# 預設使用的資料庫檔案名稱
default_db_name = "gsc.db"

[logging]
# 生產環境的預設日誌級別
level = "INFO"
